### PR TITLE
Throw an exception if a closure is called with the wrong number of ar…

### PR DESCRIPTION
**Pull request by rain-1**
…guments

### CODE REVIEW

**Comment by amirouche** [comment]
LGTM!

**Comment by yhara** [comment]
@amirouche there's one more failing test (see #129)

**Comment by yhara** [comment]
Shortest case to reproduce:

```scm
(define-macro (foo) 1)
(foo)
;=> Error: [["constant", 1, ["return"]]] is not a function []
```

**Comment by yhara** [comment]
Merged via #151.

**Pull request merged**
