### PR TITLE
[WIP] #229 - remove underscore js as a dependency

### PR DESCRIPTION
**Pull request by vidjuheffex**
Work in progress but wanted to create the PR so people know this is being worked on, and I have a few questions.

What is the proper way to load in jquery to pass tests while developing on biwa? As I go, I'm running tests and my browsers tests are failing due to $ being undefined. I'm also running into issues run `npm run build` due to jquery as well with output that says:

```
> npm run build

> biwascheme@0.7.4 build C:\Users\julia\code\biwascheme
> rollup -c


src/main-node.js → release/node_biwascheme.js...
(!) Circular dependencies
src\system\_writer.js -> src\system\pair.js -> src\system\_writer.js
src\system\_writer.js -> src\system\pair.js -> src\system\set.js -> src\system\error.js -> src\system\_writer.js
created release/node_biwascheme.js in 2.9s

src/main-browser.js → release/biwascheme.js, release/biwascheme-min.js, release/biwascheme.mjs...
(!) Circular dependencies
src\system\_writer.js -> src\system\pair.js -> src\system\_writer.js
src\system\_writer.js -> src\system\pair.js -> src\system\set.js -> src\system\error.js -> src\system\_writer.js
[!] (plugin rollup-plugin-prettier) SyntaxError: Unexpected token, expected ";" (6:14)
  4 |  * Copyright (c) 2007-2021 Yutaka HARA (http://www.biwascheme.org/)
  5 |  * Licensed under the MIT license.
> 6 |  */jquery-3.6.0.js
    |              ^
  7 | var BiwaScheme = (function () {
  8 |   //
  9 |   // variables
undefined (undefined:undefined)
SyntaxError: Unexpected token, expected ";" (6:14)
  4 |  * Copyright (c) 2007-2021 Yutaka HARA (http://www.biwascheme.org/)
  5 |  * Licensed under the MIT license.
> 6 |  */jquery-3.6.0.js
    |              ^
  7 | var BiwaScheme = (function () {
  8 |   //
  9 |   // variables
    at e (C:\Users\julia\code\biwascheme\node_modules\prettier\parser-babel.js:1:282)
    at Object.parse (C:\Users\julia\code\biwascheme\node_modules\prettier\parser-babel.js:1:262451)
    at Object.parse (C:\Users\julia\code\biwascheme\node_modules\prettier\index.js:11370:19)
    at coreFormat (C:\Users\julia\code\biwascheme\node_modules\prettier\index.js:14784:25)
    at format (C:\Users\julia\code\biwascheme\node_modules\prettier\index.js:15019:75)
    at formatWithCursor (C:\Users\julia\code\biwascheme\node_modules\prettier\index.js:15035:12)
    at C:\Users\julia\code\biwascheme\node_modules\prettier\index.js:51620:12
    at Object.format (C:\Users\julia\code\biwascheme\node_modules\prettier\index.js:51640:12)
    at RollupPluginPrettier.reformat (C:\Users\julia\code\biwascheme\node_modules\rollup-plugin-prettier\dist\index.js:110:29)
    at Object.renderChunk (C:\Users\julia\code\biwascheme\node_modules\rollup-plugin-prettier\dist\index.js:180:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! biwascheme@0.7.4 build: `rollup -c`
npm ERR! Exit status 1
```

Lastly, `_.escape` has no vanillajs equivalent, so I've created a helper file in system with the code from lodash (as its more straightforwad than underscores implementation of escape)

Is this how this should be handled?

### CODE REVIEW

**Comment by vidjuheffex** [comment]
I will add that, despite the `npm run build` failures I do generate the other files fine and can run tests that pass (besides the browser tests)

**Comment by vidjuheffex** [comment]
oh goddamn it my vscode has prettier enabled and is having opinions all over the place on the formatting :/

**Comment by yhara** [comment]
> Lastly, _.escape has no vanillajs equivalent, so I've created a helper file in system with the code from lodash (as its more straightforwad than underscores implementation of escape)
> Is this how this should be handled?

Yes, that's what I did to remove dependency on underscore.string (82fb9936a10294d2c52cb3315313d20ca6822978).

**Comment by vidjuheffex** [comment]
@yhara and regarding the jquery loading if you don't mind me asking?

**Comment by yhara** [comment]
@vidjuheffex oh is it still happening?

> As I go, I'm running tests and my browsers tests are failing due to $ being undefined.

ae689ec3 passes all the tests on my environment. (`401 examples0 failures0 errors100% done11.927 secs`) Please try this:  https://github.com/biwascheme/biwascheme/commit/9cf6f3bd217f242247c5567006d9a6b15459a24d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R77-R81

`rollup -c` also showed no error. Do you have any modification in addition to  ae689ec3 ?

**Comment by vidjuheffex** [comment]
Thanks, ( i thought I'd done that, it worked just now on my Linux box, I'll try again on my windows machine in case that had anything to do with it) much appreciated

**Comment by vidjuheffex** [comment]
Last question (for now haha), how bad is the prettier.js plugin snafu...  It didn't take too long to do this so far so I'd likely start over. but was going to hold off in case prettier becomes/could become part of the dev config.

**Comment by yhara** [comment]
Hmm, it looks like prettier is not needed actually. I thought the output is compressed without prettier, but not really.
You could include this patch to this PR if it still raises error.

```diff
diff --git a/rollup.config.js b/rollup.config.js
index 82fcdcd..05a11c0 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -1,5 +1,4 @@
 import { readFileSync } from 'fs';
-import prettier from "rollup-plugin-prettier";
 import { terser } from "rollup-plugin-terser";
 import replace from "@rollup/plugin-replace";
 import child_process from "child_process";
@@ -25,7 +24,7 @@ let replaceVersion = () =>

 export default [
   {
-    plugins: [prettier({ parser: "babel" }), replaceVersion()],
+    plugins: [replaceVersion()],
     input: "src/main-node.js",
     output: [
       {
@@ -38,7 +37,7 @@ export default [
   },
   {
     input: "src/main-browser.js",
-    plugins: [prettier({ parser: "babel" }), replaceVersion()],
+    plugins: [replaceVersion()],
     output: [
       {
         file: "release/biwascheme.js",
```

**Comment by vidjuheffex** [comment]
I just mean, do you mind the fact that this PR would re-format so much code? If not I can proceed as is

**Comment by yhara** [comment]
Oh I got it! Thank you for clarification.
Well I'm not going to add prettier to dev dependency, so could you remove the prettier diffs if you don't mind?

By the way this PR is really helpful. I'm looking forward to merge it.

**Comment by vidjuheffex** [comment]
Closing in favor of the new PR I've opened (with less mess)

**Pull request closed without merging**
