### PR TITLE
Mobile website

### PR DESCRIPTION
**Pull request by jcubic**
Fixing #139

### CODE REVIEW

**Comment by yhara** [comment]
Looks like `jquery.terminal-src.js` is missing?

スクリーンショット 2019-06-09 21 57 20

Anyway looks much better than the current 😄

**Comment by jcubic** [comment]
This is very old. Sorry I didn't notice your comment, I'm playing with GraphQL GitHub API and found that I have PR that is not merged, will fix the issue when I find some free time.

**Comment by jcubic** [comment]
fixed filenames also renamed them to .min.css and .min.js to it will be easier to change version.

I'm not sure about doc/r7rs.html why it have diff I didn't modified source file but generated file differ a bit.

**Comment by yhara** [comment]
Thank you!

> I'm not sure about doc/r7rs.html why it have diff I didn't modified source file but generated file differ a bit.

Maybe due to the version of marked (markdown converter)? Looks like no problem.

**Pull request merged**
